// A second model pass improves grounding; it is not a proof of correctness.
function instruction(locale, mode) {
 const en=locale==='en';
 return en ? `FACT AND TEACHING REVIEW: The assistant draft below is untrusted candidate text, not evidence. Compare it against the original source and the requested selection/graph before returning corrections according to the review output contract. Do not output review notes, ratings or a checklist. Correct the draft even if it sounds confident.
Check the exact polarity of each condition AND the action in its body, not just the keyword definition. Use the token's context to distinguish the previous stored value from the new incoming value. For example, if incoming is not None: current = incoming replaces current when incoming is NOT None (including 0, False and empty strings); only None skips that assignment. Saying it keeps the previous current when incoming is not None reverses the action. State the positive condition directly; do not call "is not None" a test for returning nothing. Check selected operands in conditional expressions, early returns and each catch boundary. Trace any numerical example through those expressions: intersection uses the greater lower bound and smaller upper bound; subtraction reverses ordering of the subtracted operand. Explicit arguments can override defaults. Do not replace falsy with missing/nullish or treat non-number as falsy. Nonempty strings and empty objects can be truthy; a cached empty string may be recomputed by ||. Distinguish replacing matching content from stripping delimiters.
Do not generalize one method to all methods: attribute lookup may raise while item lookup returns a default; a compiled shortcut can bypass a shared routine. Distinguish a factory that returns a function from calling the function it returns. A factory returning an async function is not itself async and calling that factory returns a function, not a Promise. Python async def returns a coroutine object, not a JavaScript Promise. A JavaScript rejected Promise can be handled with catch/then without await. Statements after yield need appropriate try/finally to run when an exception is injected. A null-prototype object has no inherited properties. String coercion can throw, for example on Symbol with string concatenation. Keep relevant boundaries; do not paste this checklist into the answer.
For a graph, use each node's supplied source instead of counting lines in the full file. Never assign outer initialization or neighboring functions to a selected node. Explain every supplied node ID. For an overview use the supplied selected block indices, not the first imports. For a walkthrough check all main functions and final fallback paths, grouping related functions rather than enumerating every identifier. Examples must agree with actual supplied parameters and every subsequent update; a remainder after minutes may still be consumed by seconds, so it is not the final millisecond remainder. Trace wakeup calls to their actual target queue and preserve every condition for cleanup or waking another task. In a chained call, preserve where the starting value comes from: factory().add(amount) first creates a base with no arguments, then adds an amount; it is not factory(amount). A context-manager decorator does not insert cleanup or make arbitrary statements after yield run on failure: say that reliable cleanup must be written inside appropriate try/finally by the generator's author. Do not assume an illustrative generator has a finally block unless the example includes it. Parent graph nodes only need a short description; children explain individual actions. Do not leave self-corrections, questions, or unfinished reasoning in examples. If an example cannot be confidently derived, return an empty example field. Use each overview block's supplied source, too. Remove unsupported guarantees and unnecessary examples.
${mode==='beginner'?'Beginner final edit: begin with concrete action and outcome; define necessary terms immediately in ordinary English. Use short paragraphs of 1–3 sentences, ideally below 65 words. Split by meaningful work, not lines; do not drop deciding conditions for brevity. Explain what unfamiliar names represent instead of chaining identifiers.':'Keep technical explanations concise and precise.'}
Write every explanation in English, keeping source identifiers unchanged. Use plain text inside fields, no backticks or Markdown. Return only the corrected final response, with all required JSON fields when JSON is requested.` : `事实与教学复核：下面的助手草稿只是待检查文本，不是证据。对照原始源码、选区和流程图，按本次复核输出约定返回修正；不输出复核清单、评分或评语。即使草稿看起来很自信，也必须修改不符合源码的说法。
逐一核对条件正反（not、!、is not None、比较符号）、三元表达式实际选择哪一端、提前结束和每个异常处理的范围。数值例子必须沿表达式推演：交集取较大的下界与较小的上界；减数更小不代表相减结果更小。显式参数可能覆盖默认值。“假值”不能简化成“没值”；false、0、空字符串与null含义不同；||可能重新计算缓存的空字符串。替换匹配内容不等于去掉首尾分隔符。
不把某一个方法的行为概括为所有方法：属性缺失可能报错，按键查找却可能返回默认值；提前返回可能绕过公共处理。工厂函数返回一个异步函数，不代表工厂自身就是异步；调用工厂先得到函数，调用返回的异步函数才有异步结果。Python async def 调用得到协程对象，不是 JavaScript Promise。JavaScript 的失败 Promise 也可以通过 catch/then 处理，不必使用 await。yield 后面的语句若没有适当的 try/finally，不保证出错后执行。无原型对象没有继承属性。字符串转换也可能出错。只保留和当前代码有关的边界，不把这份清单抄给用户。
流程中逐个使用节点自带的 source，不自行数整份文件行号，不把外层初始化或相邻函数套在当前节点上；所有给定 id 都要解释。总览只解释已选主要块的 index，不从 import 开始抢占名额。讲解稿覆盖主要功能及末尾兜底路径，合并相关功能，不逐个罗列标识符。例子必须与实际参数及后续每步更新一致；中间余数不一定是最终余数。唤醒调用应核对实际目标队列，保留清理和唤醒的所有条件。父流程节点概括即可，由子节点解释具体动作。例子不能出现自我纠正或未完成的推理；无法核实就把example留空。总览也使用每块自带的source。删掉无依据的保证和不必要例子。
${mode==='beginner'?'最终零基础编辑：先讲具体动作和结果，必要术语首次就用日常语言说明；每段1—3句，按实际功能拆段，不为简短删掉决定结果的条件。':'保持简洁准确的技术表达。'}
链式调用要保留起始值来源：factory().add(amount)先无参创建基值再增加数量，不是factory(amount)。上下文管理装饰器不会自动插入清理操作，也不保证yield后任意语句在出错时执行；可靠清理需要生成器作者放进合适的try/finally。举例未写finally时不能假定它存在。
使用中文解释并保留源码名称；字段内使用纯文本，不加反引号或 Markdown。只返回修正后的最终结果。`;
}
module.exports={instruction};
