const {chromium}=require(process.env.WHO_PLAYWRIGHT_MODULE||'playwright'),fs=require('fs'),path=require('path'),assert=require('node:assert/strict');process.chdir(path.resolve(__dirname,'..'));
(async()=>{const b=await chromium.launch({channel:'msedge',headless:true});try{const p=await b.newPage({viewport:{width:1440,height:1000}}),errors=[],checks=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:43127/?v=0.6.0');
async function load(file){if(await p.locator('#mapSource').isVisible()&&!await p.locator('#source').isVisible())await p.locator('#mapSource').click();await p.locator('#fileInput').setInputFiles(file);await p.locator('#analyzeBtn').click();await p.waitForFunction(()=>!document.querySelector('#analyzeBtn').disabled&&document.querySelector('.module-node'));}
for(let pass=0;pass<2;pass++)for(const file of ['tests/fixtures/user-credentials.sh','tests/fixtures/user-credentials-copied.txt']){await load(file);assert.match(await p.locator('#structureSummary').innerText(),/Shell/);assert.equal(await p.locator('.module-node').count(),3);assert.match(await p.locator('#functionOverview').innerText(),/仍优先/);assert.ok(await p.locator('.flow-loop').count());assert.ok(await p.locator('.flow-break').count());await p.locator('.flow-condition').filter({hasText:'后面要用的工具找得到吗？'}).click();assert.match(await p.locator('.source-focus').innerText(),/command -v security/);assert.ok(await p.locator('.knowledge-card[data-concept="sh.command"]').count());assert.equal(await p.locator('.knowledge-card[data-concept^="js."]').count(),0);checks.push(file+' pass '+pass);}
await p.waitForFunction(()=>document.getElementById('toast').hidden);await p.locator('.flow-workspace').screenshot({path:'.browser-artifacts/shell-main.png'});
await p.locator('.module-node[data-function="load_opensky_oauth_from_file"]').click();await p.locator('.flow-node').filter({hasText:'交给 JavaScript 处理，再收集文字结果'}).click();assert.match(await p.locator('.knowledge-gaps').innerText(),/未通过语法检查/);assert.match(await p.locator('.node-code').innerText(),/raw\\\.clientId/);await p.locator('#nodeStudy').screenshot({path:'.browser-artifacts/shell-embedded.png'});
// A full paste must drop a stale JavaScript filename. Dispatch the same clipboard event
// before filling because headless permissions do not give access to the user's clipboard.
await load('tests/fixtures/distance-learning.js');await p.locator('#mapSource').click();await p.evaluate(()=>{const t=document.querySelector('#source');t.setSelectionRange(0,t.value.length);const dt=new DataTransfer();dt.setData('text/plain','shell replacement');t.dispatchEvent(new ClipboardEvent('paste',{bubbles:true,clipboardData:dt}));});await p.locator('#source').fill(fs.readFileSync('tests/fixtures/user-credentials.sh','utf8'));await p.locator('#analyzeBtn').click();await p.waitForFunction(()=>!document.querySelector('#analyzeBtn').disabled);assert.match(await p.locator('#structureSummary').innerText(),/Shell/);assert.match(await p.locator('#filename').innerText(),/未命名/);checks.push('full paste clears stale file type');
await p.locator('.flow-condition').first().click();await p.setViewportSize({width:390,height:844});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.waitForFunction(()=>document.getElementById('toast').hidden);await p.locator('#nodeStudy').screenshot({path:'.browser-artifacts/shell-mobile.png'});assert.deepEqual(errors,[]);fs.writeFileSync('.browser-artifacts/shell-report.json',JSON.stringify({checks,errors},null,2));console.log('PASS shell sample twice, copy damage, embedded boundary, stale filename, source focus and mobile.');}finally{await b.close();}})().catch(e=>{console.error(e);process.exit(1)});
