const {test}=require('node:test'),assert=require('node:assert/strict'),{spawn}=require('node:child_process'),{once}=require('node:events'),vm=require('node:vm'),{analyze}=require('../analyzer');
test('actual HTTP module and optional flow routes forward the canonical block selector without model calls',async()=>{
 const bootstrap=`const http=require('node:http'),create=http.createServer;http.createServer=function(...args){const server=create.apply(this,args),listen=server.listen;server.listen=function(...values){const callback=values.pop();values.push(function(){callback.call(this);process.send({port:server.address().port});});return listen.apply(server,values);};return server;};const pick=async(result,source,start,config,options)=>{const g=require('./public/flow-model').scaffold(result,start,options.locale,{end:options.end,role:options.role,blockId:options.blockId});return {start:g.start,end:g.end,name:g.name,blockId:options.blockId,role:options.role,locale:options.locale,mode:options.readingMode};};require('./ai/ai-flow').explainFlow=pick;require('./ai/ai-module-reading').explainModule=pick;require('./server');`;
 const probe=require('node:net').createServer();await new Promise(resolve=>probe.listen(0,'127.0.0.1',resolve));const port=probe.address().port;await new Promise(resolve=>probe.close(resolve));
 const child=spawn(process.execPath,['-e',bootstrap],{cwd:require('node:path').resolve(__dirname,'..'),env:{...process.env,CODELINGO_PORT:String(port)},windowsHide:true,stdio:['ignore','ignore','pipe','ipc']});let stderr='';child.stderr.on('data',data=>stderr+=data);const watchdog=setTimeout(()=>child.kill(),15000);
 try{
  const ready=await Promise.race([once(child,'message').then(([value])=>value),once(child,'exit').then(([code])=>{throw Error('Test server exited: '+code);})]);const base='http://127.0.0.1:'+ready.port,config=await (await fetch(base+'/config.js')).text(),ctx={window:{}};vm.runInNewContext(config,ctx);assert.ok(ctx.window.APP_TOKEN);
  const source='function first() { return 1; } function second() { return 2; } const result=second();',r=analyze(source,'same.js'),targets=r.blocks.filter(b=>b.reusable||b.role==='script-entry');
  for(const block of targets)for(const route of ['module-reading','flow']){const response=await fetch(base+'/api/'+route,{method:'POST',headers:{'Content-Type':'application/json','X-CodeLingo-Token':ctx.window.APP_TOKEN},body:JSON.stringify({code:source,name:'same.js',start:block.start,end:block.end,role:block.role,blockId:block.blockId,locale:'en',readingMode:'standard',config:{model:'test'}})});assert.equal(response.status,200);const body=await response.json();assert.deepEqual(body,{start:block.start,end:block.end,name:block.title,blockId:block.blockId,role:block.role,locale:'en',mode:'standard'});}
 }finally{clearTimeout(watchdog);child.kill();if(child.exitCode===null)await once(child,'exit');}
});
