const {test}=require('node:test'),assert=require('node:assert/strict'),{analyze}=require('../analyzer'),structure=require('../public/structure'),flow=require('../public/flow-model'),reading=require('../ai-module-reading');
const source='function summarizeScores(scores) {\n  const good = scores.filter(score => score >= 60);\n  const total = good.reduce((sum, score) => sum + score, 0);\n  return { count: good.length, total };\n}\n\nconst result = summarizeScores([58, 72, 91]);\nconsole.log(result);';
test('the file entry contains initialization and print without extending a function or executing source',()=>{
 for(const name of ['scores.js','scores.ts']){const r=analyze(source,name),modules=structure.modules(r).map(x=>x.block);assert.deepEqual(modules.map(b=>[b.role,b.start,b.end]),[['named-function',1,5],['script-entry',7,8]]);const entry=flow.scaffold(r,7,'en',{end:8,role:'script-entry'});assert.deepEqual(entry.nodes.map(n=>[n.start,n.end]),[[7,7],[8,8]]);assert.deepEqual(entry.nodes[0].calls,[{name:'summarizeScores',start:1,line:7}]);assert.equal(r.blocks[0].code,source.split('\n').slice(0,5).join('\n'));}
});
test('separated top-level regions, function-only files and nonexecuting declarations retain exact ownership',()=>{
 const source='const values = [1, 2];\nfunction first(x) { return x; }\nconst result = first(values);\nfunction second(x) { return x; }\nconsole.log(result);';const r=analyze(source,'regions.js');assert.deepEqual(structure.modules(r).filter(x=>x.block.role==='script-entry').map(x=>[x.block.start,x.block.end]),[[1,1],[3,3],[5,5]]);
 for(const code of ['function first() { return 1; }\nfunction second() { return 2; }','import { tool } from "tools";\ninterface Data { value: number }\ntype Alias = Data;\ndeclare const external: number;'])assert.equal(analyze(code,'definitions.ts').blocks.filter(b=>b.role==='script-entry').length,0);
 const duplicates=analyze('function work() { return 1; }\nfunction work() { return 2; }\nconst result=work();','duplicate.js');assert.equal(duplicates.framework.links.length,0);
});
test('same-line function and initialized entry are separately selected; callbacks are not top-level steps',()=>{
 const code='const fn = () => 1, value = 2;\nconsole.log(value);',r=analyze(code,'mixed.js'),blocks=structure.modules(r).map(x=>x.block);const fn=blocks.find(b=>b.kind==='function'),entry=blocks.find(b=>b.role==='script-entry');assert.ok(fn&&entry);assert.equal(fn.start,entry.start);assert.equal(flow.scaffold(r,1,'en',{end:fn.end,role:fn.role}).name,'fn');const g=flow.scaffold(r,1,'en',{end:entry.end,role:entry.role});assert.equal(g.name,'文件入口');assert.deepEqual(g.nodes.map(n=>n.start),[1,2]);assert.throws(()=>reading.moduleInput(r,code,1,1,'mixed.js','en','script-entry'),/找不到/);
 const py=analyze('def twice(value):\n    return value * 2\n\nresult = twice(3)\nprint(result)','example.py',process.env.CODELINGO_PYTHON||'python');const modules=structure.modules(py);assert.equal(modules.filter(x=>x.block.kind==='function').length,1);assert.ok(modules.some(x=>x.block.kind==='module'));
});
test('strict title mapping rejects duplicate, missing, unknown and malformed ids, preserving parser topology',()=>{
 const graph=flow.scaffold(analyze(source,'scores.js'),1,'en'),nodes=graph.nodes.map(n=>({id:n.id,title:'Action '+n.id})),fields={summary:'First.\n\nSecond.',input:'Numbers',output:'Count and total'};
 const parsed=reading.decode(JSON.stringify({...fields,nodes}),graph.nodes);assert.equal(parsed.summary,fields.summary);assert.deepEqual(parsed.nodes.map(n=>[n.start,n.end,n.terminal]),graph.nodes.map(n=>[n.start,n.end,n.terminal]));assert.ok(parsed.nodes.every(n=>n.origin==='ai-module-title'&&!n.explanation));
 for(const bad of [nodes.slice(1),[nodes[0],nodes[0],nodes[2]],nodes.map((n,i)=>i? n:{...n,id:'new'}),nodes.map((n,i)=>i?n:{...n,title:''}),nodes.map((n,i)=>i?n:{...n,range:1}),nodes.map((n,i)=>i?n:{...n,title:'x'.repeat(161)}),{}])assert.throws(()=>reading.decode(JSON.stringify({...fields,nodes:bad}),graph.nodes),/模块解释格式/);
});
test('top-level imports, types, classes, declarations and export remain locatable without executable function bodies',()=>{
 const code='import { tool } from "tools";\ninterface Data { value: number }\ntype Alias = Data;\nclass Box { value = 1; }\nfunction work(x: number) { return x; }\nlet value;\nconst answer = work(3);\nexport { work };',r=analyze(code,'regions.ts'),modules=structure.modules(r).map(x=>x.block);
 for(let line=1;line<=8;line++)assert.ok(modules.some(b=>b.start<=line&&b.end>=line),'top line '+line);assert.deepEqual(modules.filter(b=>b.role==='script-entry').map(b=>[b.start,b.end]),[[6,7]]);assert.ok(modules.filter(b=>[1,2,3,4,8].includes(b.start)).every(b=>b.role==='file-declaration'));assert.equal(modules.find(b=>b.title==='work').kind,'function');
});
test('same-line separate entry regions have distinct parser ids and selectors',()=>{
 const code='const before=1; function work() { return 2; } const after=3;',r=analyze(code,'same.js'),entries=structure.modules(r).map(x=>x.block).filter(b=>b.role==='script-entry');assert.equal(entries.length,2);assert.notEqual(entries[0].blockId,entries[1].blockId);for(const b of entries){const g=flow.scaffold(r,b.start,'en',{end:b.end,role:b.role,blockId:b.blockId});assert.equal(g.nodes[0].startColumn,b===entries[0]?0:code.indexOf('const after'));}
});
test('nested title merge preserves branches and confirmed call targets; invalid mapping fails one production dispatch',async()=>{
 const code='function helper(value) { return value; }\nfunction work(value) {\n  if (value) { return helper(value); }\n  return 0;\n}',r=analyze(code,'nested.js'),input=reading.moduleInput(r,code,2,5,'nested.js','en','named-function'),flat=[];const walk=ns=>ns.forEach(n=>{flat.push({id:n.id,title:'Title '+n.id});n.branches.forEach(b=>walk(b.nodes));});walk(input.scaffold);
 const value=reading.decode(JSON.stringify({summary:'Work',input:'value',output:'result',nodes:flat}),input.scaffold);assert.equal(value.nodes[0].branches.length,input.scaffold[0].branches.length);assert.deepEqual(value.nodes[0].calls,input.scaffold[0].calls);assert.ok(value.nodes[0].calls.length);
 const previous=globalThis.fetch;let count=0;globalThis.fetch=async()=>{count++;return Response.json({choices:[{finish_reason:'stop',message:{content:JSON.stringify({summary:'Work',input:'value',output:'result',nodes:flat.slice(1)})}}]});};try{await assert.rejects(()=>reading.explainModule(r,code,2,{base:'https://api.deepseek.com',model:'deepseek-flash'},{end:5,role:'named-function',locale:'en',readingMode:'standard'}),/模块解释格式/);assert.equal(count,1);}finally{globalThis.fetch=previous;}
});
test('separate same-line declarations keep canonical parser block identities',()=>{const r=analyze('function first() { return 1; } function second() { return 2; } const value=first();','same.js'),blocks=structure.modules(r).map(x=>x.block);assert.equal(new Set(blocks.map(b=>b.blockId)).size,blocks.length);for(const b of blocks){const g=flow.scaffold(r,b.start,'en',{end:b.end,role:b.role,blockId:b.blockId});assert.equal(g.name,b.title);}});
test('module selection retains blockId evidence even when a parser has no role label',async()=>{
 const code='function first() { return 1; } function second() { return 2; }',r=analyze(code,'two.js');for(const b of r.blocks)delete b.role;const second=r.blocks.find(b=>b.title==='second'),previous=globalThis.fetch;let count=0,input;
 globalThis.fetch=async(url,req)=>{count++;input=JSON.parse(JSON.parse(req.body).messages[1].content);return Response.json({choices:[{finish_reason:'stop',message:{content:JSON.stringify({summary:'Second function',input:'No explicit arguments',output:'2',nodes:[{id:'n1',title:'Return 2'}]})}}]});};try{const result=await reading.explainModule(r,code,second.start,{base:'https://api.deepseek.com',model:'deepseek-flash'},{end:second.end,blockId:second.blockId,readingMode:'standard',locale:'en'});assert.equal(count,1);assert.equal(result.nodes[0].startColumn,code.lastIndexOf('return'));assert.equal(input.source,code);}finally{globalThis.fetch=previous;}
});
