const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
class Node {
 constructor(tag,text='',cls=''){this.tagName=tag.toUpperCase();this.textContent=text||'';this.className=cls;this.children=[];this.dataset={};this.style={};this.hidden=false;this.listeners={};this.classList={add:c=>{this.className+=' '+c;},remove:c=>{this.className=this.className.split(' ').filter(x=>x!==c).join(' ');},toggle:(c,on)=>{this.classList.remove(c);if(on)this.classList.add(c);},contains:c=>this.className.split(' ').includes(c)};}
 append(...nodes){this.children.push(...nodes);} insertBefore(node,ref){const i=this.children.indexOf(ref);this.children.splice(i<0?this.children.length:i,0,node);} replaceChildren(...nodes){this.children=[...nodes];} setAttribute(k,v){(this.attributes??={})[k]=String(v);} addEventListener(type,fn){this.listeners[type]=fn;} click(){return this.onclick?.();} focus(options){Node.active=this;this.focusOptions=options;} contains(node){return this.children.some(child=>child===node||child.contains(node));}
 querySelector(selector){return this.querySelectorAll(selector)[0]||null;} querySelectorAll(selector){const found=[];for(const child of this.children){if(selector.startsWith('.')&&child.className.split(' ').includes(selector.slice(1)))found.push(child);found.push(...child.querySelectorAll(selector));}return found;}
}
function setup(scriptFile=require.resolve('../public/studio.js')){
 const elements=new Map(),requests=[],saved=[],a={start:1,end:3,title:'first',kind:'function'},b={start:4,end:6,title:'second',kind:'function'};
 const $=id=>{if(!elements.has(id))elements.set(id,new Node('div'));return elements.get(id);};
 const context=vm.createContext({console,AbortController,AbortSignal,setInterval,clearInterval,Date,Map,Set,JSON,analyzedSource:'function first() {\n return 1;\n}\nfunction second() {\n return 2;\n}',fileName:'two.js',config:{model:'chosen',base:'example'},readingMode:'beginner',sourceOffset:0,current:{language:'JavaScript',blocks:[a,b]},WhoI18n:{locale:'zh-CN'},WhoStructure:{modules:r=>r.blocks.map(block=>({block}))},WhoFlowModel:{scaffold:()=>({nodes:[]})},WhoPointDisplay:{paragraph:text=>new Node('p',text)},element:(...args)=>new Node(...args),$,document:{addEventListener(){},body:new Node('body')},window:{addEventListener(){}},connected:()=>true,beginnerMode:()=>true,settings(){},selectionQuestion:()=>'Explain the selected line.',appendBuiltinReference(){},appendExplanationSave:(host,answer)=>saved.push(answer),explanationSource:()=>({}),appendAITerms(){throw Error('Module must not append terms');},api:(route,body,method,signal)=>new Promise((resolve,reject)=>{requests.push({route,body,signal,resolve,reject});signal.addEventListener('abort',()=>reject(new Error('aborted')));})});
 Object.defineProperty(context.document,'activeElement',{get:()=>Node.active});vm.runInContext(fs.readFileSync(scriptFile,'utf8'),context);return {context,requests,saved,$,a,b,run:code=>vm.runInContext(code,context)};
}
const answer=summary=>({summary,input:'Numbers received.',output:'Result returned.',nodes:[]}),settle=()=>new Promise(resolve=>setImmediate(resolve));
test('module click deduplicates, renders summary above one IO frame and does not auto-generate flow',async()=>{
 const s=setup();s.run('studioOpenFunction(current.blocks[0])');s.run('studioOpenFunction(current.blocks[0])');assert.equal(s.requests.length,1);assert.equal(s.requests[0].route,'module-reading');s.requests[0].resolve(answer('Two paragraphs.\n\nComplete result.'));await settle();
 const children=s.$('studioExplain').children,frame=children.find(n=>n.className==='studio-io');assert.equal(frame.children.length,2);assert.ok(children.findIndex(n=>n.textContent.startsWith('Two paragraphs'))<children.indexOf(frame));assert.equal(s.saved[0],'Two paragraphs.\n\nComplete result.\n\n输入：Numbers received.\n\n输出：Result returned.');
 s.run('studioOpenFunction(current.blocks[0])');assert.equal(s.requests.length,1);
 const tree=s.run('studioFunction(current.blocks[0],[])');tree.querySelector('.studio-map-expand').click();assert.equal(s.requests.length,1);assert.equal(s.$('studioFlow').querySelector('.studio-detailed-flow'),null);assert.ok(s.$('studioExplain').children.some(n=>n.textContent.startsWith('Two paragraphs')));
});
test('rapid module switch and stop protect the selected explanation',async()=>{
 const s=setup();s.run('studioOpenFunction(current.blocks[0])');s.run('studioOpenFunction(current.blocks[1])');s.requests[1].resolve(answer('SECOND'));await settle();s.requests[0].resolve(answer('FIRST'));await settle();assert.ok(s.$('studioExplain').children.some(n=>n.textContent==='SECOND'));assert.ok(!s.$('studioExplain').children.some(n=>n.textContent==='FIRST'));
 s.run('studioReset();studioOpenFunction(current.blocks[0])');s.$('studioStop').click();assert.equal(s.requests[2].signal.aborted,true);await settle();assert.ok(!s.$('studioExplain').children.some(n=>n.textContent==='FIRST'));assert.ok(s.$('studioExplain').querySelector('.studio-module-generate'));
});
test('cache identity tracks source, filename, config values, model, mode and locale',async()=>{
 const s=setup();s.run('studioGetModule(current.blocks[0])');s.requests[0].resolve(answer('cached'));await settle();
 for(const mutation of ['analyzedSource += "\\n"','fileName="renamed.js"','config.base="changed"','config.model="another"','readingMode="standard"','WhoI18n.locale="en"']){const before=s.requests.length;s.run(mutation+';studioGetModule(current.blocks[0])');assert.equal(s.requests.length,before+1,mutation);s.requests.at(-1).resolve(answer('current'));await settle();}
 const before=s.requests.length;s.run('config={...config};studioGetModule(current.blocks[0])');assert.equal(s.requests.length,before,'equal config values reuse cache');
 const cancelled=s.run('studioReset();studioGetModule(current.blocks[0])');const rejection=assert.rejects(cancelled,/已停止/);const old=s.requests.at(-1);s.run('readingMode="beginner";studioIdentity()');assert.equal(old.signal.aborted,true);await rejection;await settle();
});

test('an old module button synchronizes changed identity before delivering its new response',async()=>{
 const s=setup();s.run('studioIdentity();studioShowFunction(current.blocks[0])');const button=s.$('studioExplain').querySelector('.studio-module-generate');s.run('config.model="changed"');const request=button.click();assert.equal(s.requests.length,1);assert.equal(s.requests[0].body.config.model,'changed');s.requests[0].resolve(answer('NEW CONFIG'));await request;assert.ok(s.$('studioExplain').children.some(n=>n.textContent==='NEW CONFIG'));
});test('the production api wrapper sends module mode, locale and effective model in actual HTTP JSON',async()=>{
 const app=fs.readFileSync(require.resolve('../public/app.js'),'utf8'),apiSource=app.split('\n').find(line=>line.startsWith('async function api('));assert.ok(apiSource);
 for(const mode of ['beginner','standard'])for(const locale of ['en','zh-CN']){
  const s=setup(),bodies=[];s.context.fetch=async(url,options)=>{bodies.push(JSON.parse(options.body));return {ok:true,json:async()=>answer('HTTP')};};s.context.window.APP_TOKEN='test';s.context.readingMode=mode;s.context.WhoI18n.locale=locale;s.context.effectiveConfig=()=>({model:'effective',provider:'personal'});vm.runInContext(apiSource,s.context);
  await s.run('studioGetModule(current.blocks[0])');assert.equal(bodies.length,1);assert.equal(bodies[0].readingMode,mode);assert.equal(bodies[0].locale,locale);assert.equal(bodies[0].config.model,'effective');assert.equal(bodies[0].start,1);assert.equal(bodies[0].end,3);
 }
});
test('default module titles populate expanded scaffold without another call and title clicks request precise point reading',async()=>{
 const s=setup();s.run('studioOpenFunction(current.blocks[0])');const tree=s.run('studioFunction(current.blocks[0],[])');tree.querySelector('.studio-map-expand').click();assert.equal(s.requests.length,1);
 s.requests[0].resolve({...answer('Summary'),nodes:[{id:'n1',title:'Return the result',origin:'ai-module-title',kind:'return',start:2,end:2,branches:[],terminal:true}]});await settle();const node=s.$('studioFlow').querySelector('.studio-node');assert.ok(node.children.some(n=>n.textContent==='Return the result'));node.click();assert.equal(s.requests.length,2);assert.equal(s.requests[1].route,'ask');assert.equal(s.requests[1].body.selection.start,2);assert.equal(s.requests[1].body.selection.end,2);assert.equal(s.requests[1].body.pointReading,true);s.requests[1].resolve({answer:'Return explanation'});await settle();
});
test('same-start modules do not share cached answers or pending requests',async()=>{
 const s=setup();s.run('current.blocks[0].role="named-function";current.blocks[1]={start:1,end:3,kind:"module",role:"script-entry",title:"entry"};');const a=s.run('studioGetModule(current.blocks[0])'),b=s.run('studioGetModule(current.blocks[1])');assert.equal(s.requests.length,2);assert.notEqual(s.requests[0].body.role,s.requests[1].body.role);s.requests[0].resolve(answer('FUNCTION'));s.requests[1].resolve(answer('ENTRY'));await Promise.all([a,b]);s.run('studioOpenFunction(current.blocks[1])');assert.ok(s.$('studioExplain').children.some(n=>n.textContent==='ENTRY'));
});
test('module labels identify entry or structure, use generic loading and retain the exact request payload',async()=>{
 for(const locale of ['en','zh-CN'])for(const mode of ['beginner','standard'])for(const [kind,role,label] of [['module','script-entry','执行步骤'],['function','named-function','函数'],['class','file-declaration','类'],['type','file-declaration','类型约定'],['import','file-declaration','引入']]){
  const current=setup();
  for(const s of [current]){s.context.WhoI18n.locale=locale;s.context.readingMode=mode;s.run('current.blocks[1].kind='+JSON.stringify(kind)+';current.blocks[1].role='+JSON.stringify(role));if(locale==='en'){vm.runInContext(fs.readFileSync(require.resolve('../public/locale-en.js'),'utf8'),s.context);s.run('uiText=text=>WhoEnglish[text]||text');}s.run('studioOpenFunction(current.blocks[1])');}
  assert.equal(current.requests.length,1);assert.equal(current.requests[0].route,'module-reading');assert.equal(current.requests[0].body.start,4);assert.equal(current.requests[0].body.end,6);assert.equal(current.requests[0].body.role,role);assert.equal(current.run('studioSelectionKind'),'function');assert.ok(current.$('studioRange').textContent.startsWith(locale==='en'?current.context.WhoEnglish[label]:label));const button=current.$('studioExplain').querySelector('.studio-module-generate');assert.equal(button.textContent,locale==='en'?'Understanding this module…':'正在理解这个模块…');for(const s of [current])s.requests[0].resolve(answer('Same response'));await settle();
 }
});

for(const kind of ['module','point','followup'])for(const timing of ['before-back','after-back'])test('navigation restores pending '+kind+' '+timing+' without dispatch',async()=>{
 const s=setup();if(kind!=='module')s.context.appendAITerms=()=>{};s.run('studioIdentity();studioMapFrames=[{type:"directory"}]');
 if(kind==='module')s.run('studioOpenFunction(current.blocks[0])');
 else {s.run('studioSelect(2,2,false,"line")');if(kind==='point')s.run('studioExplainSelection()');else s.run('studioFollowup("More",studioSelected)');}
 assert.equal(s.requests.length,1);s.run('studioMapOpen(current.blocks[1],{line:2},false)');assert.equal(s.requests.length,1);
 if(timing==='before-back'){s.requests[0].resolve(kind==='module'?answer('PARENT READY'):{answer:'PARENT READY'});await settle();}
 s.run('studioMapBack()');
 if(timing==='after-back'){s.requests[0].resolve(kind==='module'?answer('PARENT READY'):{answer:'PARENT READY'});await settle();}
 assert.equal(s.requests.length,1);const host=kind==='followup'?s.$('studioExplain').querySelector('.studio-followup-answer'):s.$('studioExplain');assert.ok(host.children.some(n=>n.textContent==='PARENT READY'));assert.ok(!host.children.some(n=>n.textContent.includes('正在解释')));
});
test('free expansion, parent scroll and explanation restoration, two callsite contexts and recursion use one definition cache',async()=>{
 const s=setup();s.run('studioMapFrames=[{type:"directory"}];studioMapOpen(current.blocks[0],null,false)');assert.equal(s.requests.length,0);
 s.$('studioMapColumn').scrollTop=123;s.$('studioCode').scrollTop=77;s.$('studioExplain').replaceChildren(new Node('p','PARENT'));
 s.run('studioMapOpen(current.blocks[1],{line:2,callIndex:0},true)');assert.equal(s.requests.length,1);s.requests[0].resolve(answer('CHILD'));await settle();
 s.run('studioMapOpen(current.blocks[1],{line:5},true)');assert.equal(s.run('studioMapFrames.length'),3);assert.equal(s.requests.length,1);
 s.run('studioMapBack()');assert.equal(s.$('studioMapColumn').scrollTop,123);assert.equal(s.$('studioCode').scrollTop,77);assert.equal(s.$('studioExplain').children[0].textContent,'PARENT');
 s.run('studioMapOpen(current.blocks[1],{line:3,callIndex:1},true)');assert.equal(s.requests.length,1);assert.equal(s.run('studioMapFrames.at(-1).via.line'),3);assert.ok(s.$('studioExplain').children.some(n=>n.textContent==='CHILD'));
});
test('directory prioritizes top-level code, preserves reachable functions in collapsed directory and uses sans natural titles',()=>{
 const s=setup();s.run('current.blocks.push({start:7,end:8,kind:"module",role:"script-entry",title:"entry"});current.framework={links:[{fromStart:0,line:7,toStart:1},{fromStart:1,line:2,toStart:4}]};studioMapFrames=[{type:"directory"}];studioMapRender()');
 const cards=s.$('studioFlow').children.filter(n=>n.className==='studio-module-card');assert.equal(cards.length,1);assert.equal(cards[0].querySelector('.studio-title-natural').textContent,'这段代码');assert.equal(s.$('studioFlow').querySelector('.studio-map-directory').children.length,3);assert.equal(s.requests.length,0);
});

test('map entry moves keyboard focus to Back, returning restores expand without scrolling or dispatch',()=>{
 const s=setup();s.run('studioIdentity();studioMapFrames=[{type:"directory"}];studioMapRender()');const expand=s.$('studioFlow').querySelector('.studio-map-expand');expand.focus();expand.click();const back=s.$('studioFlow').querySelector('.studio-map-back');assert.equal(Node.active,back);assert.equal(back.focusOptions.preventScroll,true);s.$('studioMapColumn').scrollTop=90;back.click();assert.equal(Node.active,expand);assert.equal(expand.focusOptions.preventScroll,true);assert.equal(s.requests.length,1);s.requests[0].resolve(answer('Read once'));
});
test('returning after cached map rerender resolves the replacement call button rather than removed DOM',async()=>{
 const s=setup();const nodes=[{id:'n1',kind:'return',start:2,end:2,branches:[],calls:[{name:'second',start:4,line:2}]}];s.context.WhoFlowModel.scaffold=()=>({nodes});s.context.nodes=nodes;
 s.run('studioIdentity();studioMapFrames=[{type:"directory"}];studioModuleCache.set(studioBlockKey(current.blocks[0]),{...{summary:"Parent",input:"In",output:"Out"},nodes});studioMapOpen(current.blocks[0],null,false)');const old=s.$('studioFlow').querySelector('.studio-call-nav');old.focus();old.click();assert.equal(s.requests.length,1);s.requests[0].resolve(answer('Child'));await settle();s.run('studioMapBack()');const replacement=s.$('studioFlow').querySelector('.studio-call-nav');assert.notEqual(replacement,old);assert.equal(Node.active,replacement);assert.equal(replacement.dataset.callNode,'n1');assert.equal(s.requests.length,1);
});
test('English execution Return and navigation Back remain distinct labels',()=>{
 const s=setup();vm.runInContext(fs.readFileSync(require.resolve('../public/locale-en.js'),'utf8'),s.context);s.run('uiText=text=>WhoEnglish[text]||text;studioIdentity();studioMapFrames=[{type:"directory"}];studioMapOpen(current.blocks[0],null,false)');assert.equal(s.$('studioFlow').querySelector('.studio-map-back').textContent,'Back');const sequence=s.run('studioSequence([{id:"n1",kind:"return",start:2,end:2,branches:[]}],[])');assert.equal(sequence.querySelector('.studio-node').children[0].textContent,'Return');
});

test('pending parent title completion preserves restored call focus after replacing map nodes',async()=>{
 const s=setup(),nodes=[{id:'n1',kind:'return',start:2,end:2,branches:[],calls:[{name:'second',start:4,line:2}]}];s.context.WhoFlowModel.scaffold=()=>({nodes});s.run('studioIdentity();studioMapFrames=[{type:"directory"}];studioMapOpen(current.blocks[0],null,true)');assert.equal(s.requests.length,1);const original=s.$('studioFlow').querySelector('.studio-call-nav');original.focus();s.context.original=original;s.run('studioMapOpen(current.blocks[1],{line:2},false,original);studioMapBack()');assert.equal(Node.active,original);s.requests[0].resolve({...answer('Completed parent'),nodes});await settle();const replaced=s.$('studioFlow').querySelector('.studio-call-nav');assert.notEqual(replaced,original);assert.equal(Node.active,replaced);assert.equal(replaced.focusOptions.preventScroll,true);assert.equal(s.requests.length,1);
});

test('body read followed by free expand, child and Back attaches existing parent pending body and IO',async()=>{
 const s=setup(),nodes=[{id:'n1',kind:'return',start:2,end:2,branches:[],calls:[{name:'second',start:4,line:2}]}];s.context.WhoFlowModel.scaffold=()=>({nodes});s.run('studioIdentity();studioMapFrames=[{type:"directory"}];studioMapRender()');const card=s.$('studioFlow').children[0];card.querySelector('.studio-module-select').click();assert.equal(s.requests.length,1);card.querySelector('.studio-map-expand').click();assert.equal(s.requests.length,1);s.$('studioFlow').querySelector('.studio-call-nav').click();assert.equal(s.requests.length,2);s.run('studioMapBack()');s.requests[0].resolve({...answer('PARENT COMPLETE'),nodes});await settle();assert.ok(s.$('studioExplain').children.some(n=>n.textContent==='PARENT COMPLETE'));assert.equal(s.$('studioExplain').querySelector('.studio-io').children.length,2);assert.ok(!s.$('studioExplain').querySelector('.studio-module-generate'));assert.equal(s.requests.length,2);s.requests[1].resolve(answer('CHILD COMPLETE'));await settle();assert.ok(s.$('studioExplain').children.some(n=>n.textContent==='PARENT COMPLETE'));
});

test('cached entry title updates mounted and saved parent headings in place without touching navigation or IO',async()=>{
 const s=setup();s.run('current.blocks[0].kind="module";current.blocks[0].role="script-entry";studioIdentity();studioMapFrames=[{type:"directory"}];studioMapRender()');const card=s.$('studioFlow').children[0],button=card.querySelector('.studio-module-select'),title=card.querySelector('.studio-module-title');assert.equal(title.textContent,'这段代码');assert.match(button.attributes['aria-label'],/第1—3行/);assert.equal(card.querySelector('.studio-module-actions').children.length,2);
 button.click();card.querySelector('.studio-map-expand').click();const map=s.$('studioFlow'),back=map.querySelector('.studio-map-back'),heading=map.querySelector('.studio-module-title');back.focus();s.$('studioMapColumn').scrollTop=43;s.requests[0].resolve({...answer('Summary untouched'),title:'Collect visible results'});await settle();assert.equal(s.requests.length,1);assert.equal(heading.textContent,'Collect visible results');assert.equal(title.textContent,'Collect visible results');assert.equal(Node.active,back);assert.equal(s.$('studioMapColumn').scrollTop,43);assert.ok(s.$('studioExplain').querySelector('.studio-io'));s.run('studioMapBack()');assert.equal(s.$('studioFlow').children[0],card);assert.equal(button.attributes['aria-label'],'解释模块：Collect visible results，第1—3行');
});
test('source function identifier remains its identity even when model supplies decorative title',async()=>{
 const s=setup();s.run('studioOpenFunction(current.blocks[0])');s.requests[0].resolve({...answer('Complete'),title:'Other decorative heading'});await settle();assert.equal(s.$('studioExplain').children[0].textContent,'first');assert.equal(s.requests.length,1);
});

test('parent entry title completion updates saved map text while child keeps its own selection, focus and pending read',async()=>{
 const s=setup(),nodes=[{id:'n1',kind:'return',start:2,end:2,branches:[],calls:[{name:'second',start:4,line:2}]}];s.context.WhoFlowModel.scaffold=()=>({nodes});s.run('current.blocks[0].kind="module";current.blocks[0].role="script-entry";studioIdentity();studioMapFrames=[{type:"directory"}];studioMapOpen(current.blocks[0],null,true)');const parentHeading=s.$('studioFlow').querySelector('.studio-module-title');s.$('studioMapColumn').scrollTop=61;s.$('studioFlow').querySelector('.studio-call-nav').click();assert.equal(s.requests.length,2);const childHeading=s.$('studioFlow').querySelector('.studio-module-title'),back=s.$('studioFlow').querySelector('.studio-map-back');back.focus();s.requests[0].resolve({...answer('Parent body'),title:'Visible parent actions',nodes});await settle();assert.equal(parentHeading.textContent,'Visible parent actions');assert.equal(s.$('studioFlow').querySelector('.studio-module-title'),childHeading);assert.equal(childHeading.textContent,'second');assert.equal(Node.active,back);assert.equal(s.run('studioSelected.start'),4);assert.ok(s.$('studioExplain').querySelector('.studio-module-generate'));s.run('studioMapBack()');assert.equal(s.$('studioFlow').querySelector('.studio-module-title'),parentHeading);assert.equal(parentHeading.textContent,'Visible parent actions');assert.equal(s.$('studioMapColumn').scrollTop,61);assert.ok(s.$('studioExplain').querySelector('.studio-io'));s.requests[1].resolve(answer('Child done'));await settle();assert.equal(s.requests.length,2);assert.ok(s.$('studioExplain').children.some(n=>n.textContent==='Parent body'));
});

test('cold Expand automatically reads once, repeated entry reuses cache, and has no detailed-flow action',async()=>{
 const s=setup();s.run('studioIdentity();studioMapFrames=[{type:"directory"}];studioMapRender()');const card=s.$('studioFlow').children[0];card.querySelector('.studio-map-expand').click();assert.equal(s.requests.length,1);assert.equal(s.requests[0].route,'module-reading');assert.match(s.$('studioFlow').querySelector('.studio-map-status').children[0].textContent,/正在生成/);assert.equal(s.$('studioFlow').querySelector('.studio-detailed-flow'),null);s.requests[0].resolve(answer('Ready'));await settle();assert.equal(s.$('studioFlow').querySelector('.studio-map-status').hidden,true);assert.equal(s.$('studioExplain').querySelector('.studio-io').children.length,2);s.run('studioMapBack()');card.querySelector('.studio-map-expand').click();assert.equal(s.requests.length,1);
});
test('failed or canceled auto-map read offers explicit retry, never automatic retry or disconnected dispatch',async()=>{
 for(const stop of [false,true]){const s=setup();s.run('studioMapOpen(current.blocks[0],null,true)');assert.equal(s.requests.length,1);if(stop)s.$('studioStop').click();else s.requests[0].reject(Error('Observed failure'));await settle();const status=s.$('studioFlow').querySelector('.studio-map-status');assert.ok(status.querySelector('.studio-error'));assert.equal(s.requests.length,1);status.querySelector('.studio-map-retry').click();assert.equal(s.requests.length,2);s.requests[1].resolve(answer('Retry ready'));await settle();assert.equal(status.hidden,true);}
 const s=setup();s.context.connected=()=>false;s.run('studioMapOpen(current.blocks[0],null,true)');assert.equal(s.requests.length,0);s.$('studioFlow').querySelector('.studio-map-retry').click();assert.equal(s.requests.length,0);
});

test('AI-labelled unknown nodes retain parser uncertainty while normal steps do not receive that notice',()=>{
 const s=setup();for(const locale of ['zh-CN','en']){if(locale==='en'){vm.runInContext(fs.readFileSync(require.resolve('../public/locale-en.js'),'utf8'),s.context);s.run('uiText=text=>WhoEnglish[text]||text');}const unknown=s.run('studioSequence([{id:"u1",kind:"unknown",start:1,end:3,title:"Natural AI label",origin:"ai-module-title",branches:[]}],[])'),normal=s.run('studioSequence([{id:"n1",kind:"return",start:2,end:2,title:"Result",branches:[]}],[])');assert.equal(unknown.querySelector('.studio-node').children[0].textContent,locale==='en'?'Needs checking':'待核对');assert.ok(unknown.querySelector('.studio-note'));assert.equal(normal.querySelector('.studio-note'),null);}
});

test('parent failure while child is pending restores map retry and repeated retry shares one new read',async()=>{
 const s=setup();s.run('studioMapOpen(current.blocks[0],null,true);studioMapOpen(current.blocks[1],{line:2},true)');assert.equal(s.requests.length,2);s.requests[0].reject(Error('Parent failed'));await settle();assert.ok(!s.$('studioFlow').querySelector('.studio-map-status').querySelector('.studio-error'));s.run('studioMapBack()');const status=s.$('studioFlow').querySelector('.studio-map-status');assert.equal(status.querySelector('.studio-error').textContent,'Parent failed');const retry=status.querySelector('.studio-map-retry');retry.click();retry.click();assert.equal(s.requests.length,3);assert.equal(s.requests[2].route,'module-reading');s.requests[2].resolve(answer('Parent retry complete'));await settle();assert.equal(status.hidden,true);assert.equal(s.$('studioExplain').querySelector('.studio-io').children.length,2);s.requests[1].resolve(answer('Late child'));await settle();assert.ok(s.$('studioExplain').children.some(n=>n.textContent==='Parent retry complete'));assert.equal(s.requests.length,3);
});

test('pending AI titles preserve keyboard focus, open branches and scroll with nested repeated branch labels',async()=>{
 const s=setup(),leaf=(id,line)=>({id,kind:'return',start:line,end:line,branches:[]}),nodes=[{id:'n1',kind:'condition',start:1,end:3,branches:[{label:'条件成立',nodes:[{id:'n2',kind:'condition',start:2,end:2,branches:[{label:'条件成立',nodes:[leaf('n3',2)]}]}]},{label:'条件成立',nodes:[leaf('n4',3)]}]}];s.context.WhoFlowModel.scaffold=()=>({nodes});s.run('studioMapOpen(current.blocks[0],null,true)');assert.equal(s.requests.length,1);const host=s.$('studioFlow'),oldBranches=host.querySelectorAll('.studio-branch'),oldSummary=oldBranches[1].children[0];oldBranches[0].open=true;oldBranches[1].open=true;oldBranches[2].open=false;s.$('studioMapColumn').scrollTop=47;oldSummary.focus();s.requests[0].resolve({...answer('Ready'),nodes});await settle();const updated=host.querySelectorAll('.studio-branch');assert.equal(updated[0].open,true);assert.equal(updated[1].open,true);assert.equal(updated[2].open,false);assert.notEqual(updated[1].children[0],oldSummary);assert.equal(Node.active,updated[1].children[0]);assert.equal(Node.active.focusOptions.preventScroll,true);assert.equal(s.$('studioMapColumn').scrollTop,47);assert.equal(s.requests.length,1);assert.equal(host.querySelector('.studio-map-status').hidden,true);
});

test('module summary and IO share only selected source evidence while saved answer stays canonical',async()=>{
 const s=setup(),seen=[];s.context.WhoPointDisplay.paragraph=(text,language,context)=>{seen.push({text,language,context});return new Node('p',text);};s.run('studioOpenFunction(current.blocks[0])');s.requests[0].resolve(answer('first keeps its result.'));await settle();assert.equal(s.requests.length,1);assert.equal(seen.length,3);assert.ok(seen.every(row=>row.context===seen[0].context));assert.equal(seen[0].context.source,'function first() {\n return 1;\n}');assert.ok(!seen[0].context.source.includes('second'));assert.equal(s.saved[0],'first keeps its result.\n\n输入：Numbers received.\n\n输出：Result returned.');
});
