const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');const {analyze,detect}=require('../analyzer');const {prepare}=require('../prepare');const py=process.env.CODELINGO_PYTHON||'python';
const corpus=n=>fs.readFileSync(path.join(__dirname,'corpus',n),'utf8');
test('real CommonJS export has typed checks, finite-number behavior and original source',()=>{const r=analyze(corpus('is-number.js'),'is-number.js');assert.equal(r.status,'ready');assert.equal(r.blocks.filter(x=>x.kind==='function').length,1);const b=r.blocks[0];assert.equal(b.title,'module.exports');assert.match(b.purpose,/num 是数字/);assert.match(b.purpose,/两端的空白/);assert.match(b.output,/有限/);assert.ok(b.symbols.some(s=>s.name==='num'&&s.origin.includes('作者')));assert.equal(b.start,10);});
test('real TypeScript generics and multiline arrows are functions, not regex accidents',()=>{const r=analyze(corpus('vue-general.ts'),'vue-general.ts');assert.equal(r.status,'ready');for(const name of ['isString','remove','isPromise'])assert.ok(r.blocks.some(b=>b.title===name),name);const remove=r.blocks.find(b=>b.title==='remove');assert.match(remove.inputs,/arr/);assert.ok(remove.symbols.some(s=>s.name==='arr'&&s.origin==='作者命名的输入'));});
test('real workflow identifies reused workflows and conditions without inventing environments',()=>{const r=analyze(corpus('vue-ci.yml'),'ci.yml');assert.equal(r.status,'ready');assert.ok(r.blocks.some(b=>b.kind==='trigger'));const reuse=r.blocks.find(b=>b.title==='任务：test');assert.match(reuse.purpose,/复用另一份工作流/);assert.doesNotMatch(reuse.purpose,/运行环境：未提供/);assert.match(reuse.purpose,/启动前/);assert.ok(r.blocks.some(b=>b.kind==='step'&&/Node.js/.test(b.purpose)));});
test('npm lock excerpt identifies dependency declarations and does not invent locked versions',()=>{const code=JSON.stringify({name:'gods-eye-view',lockfileVersion:3,packages:{'':{dependencies:{cesium:'^1.124.0'},engines:{node:'>=24.14.0 <25 || >=26 <27'}}}},null,2);const r=analyze(code,'');assert.equal(r.language,'JSON');assert.equal(r.status,'ready');assert.match(r.summary,/安装记录/);const descend=n=>[n,...(n.children||[]).flatMap(descend)],nodes=r.blocks.flatMap(b=>(b.configurationNodes||[]).flatMap(descend));const d=nodes.find(n=>n.guide.title==='项目要用的工具');assert.match(d.guide.purpose,/范围不等于已安装/);assert.ok(nodes.some(n=>/运行环境/.test(n.guide.title)));assert.doesNotMatch(r.summary,/0 个函数/);});
test('truncated and HTML-escaped pasted JSON is not presented as verified input',()=>{const source='{\n&#x20; "name": "app",\n&#x20; "lockfileVersion": 3,\n&#x20; "packages": {';const r=analyze(source,'');assert.equal(r.language,'JSON');assert.notEqual(r.status,'ready');assert.ok(r.warnings.some(w=>w.includes('复制格式')));const clean=prepare(source);assert.equal(source.includes('&#x20;'),true);assert.ok(!clean.code.includes('&#x20;'));assert.notEqual(analyze(clean.code,'x.json').status,'ready');});
test('valid YAML matrix and malformed indentation have different outcomes',()=>{const good='name: CI\non:\n  push:\n    branches: [main]\njobs:\n  verify:\n    runs-on: ubuntu-latest\n    strategy:\n      matrix:\n        node: [24.14.0, 26.x]\n    steps:\n      - run: npm ci\n';const r=analyze(good,'ci.yml');assert.equal(r.status,'ready');assert.match(r.blocks.find(b=>b.kind==='job').purpose,/24.14.0/);assert.ok(r.blocks.some(b=>b.kind==='step'&&b.purpose.includes('锁文件')));const bad=analyze(good.split('\n').map(x=>x.trim()).join('\n'),'ci.yml');assert.notEqual(bad.status,'ready');assert.ok(bad.warnings.length);});
test('HTML and CSS explain content and appearance without running embedded script',()=>{const h=analyze('<h1>欢迎</h1><script>throw new Error("never execute")</script><button id="save">保存</button>','x.html');assert.ok(h.blocks.some(b=>b.title.includes('欢迎')));assert.ok(h.blocks.some(b=>b.purpose.includes('不执行')));const c=analyze('.save { color: red; padding: 8px; }','x.css');assert.equal(c.status,'ready');assert.match(c.blocks[0].purpose,/文字颜色：red/);assert.match(c.blocks[0].purpose,/间距：8px/);assert.equal(analyze('.save { color: red','x.css').status,'invalid');});
test('SQL separates read and write behavior, and explicitly limits dialect recovery',()=>{const r=analyze('SELECT name FROM people WHERE age > 18 ORDER BY name;','x.sql');assert.equal(r.status,'ready');assert.match(r.blocks[0].purpose,/WHERE/);const d=analyze('DELETE FROM people;','x.sql');assert.match(d.blocks[0].purpose,/未看到 WHERE/);const complex=analyze(corpus('chinook.sql'),'chinook.sql');assert.equal(complex.status,'partial');assert.equal(complex.blocks.length,11);assert.match(complex.summary,/未验证/);assert.match(complex.blocks[0].usage,/AlbumId/);});
test('real Python algorithms provide function locations and no foreign execution',()=>{const r=analyze(corpus('binary-search.py'),'x.py',py);assert.equal(r.status,'ready');const b=r.blocks.find(b=>b.title==='binary_search');assert.ok(b);assert.match(b.output,/-1/);assert.ok(b.code.startsWith('def binary_search('));});
test('shadowed JS builtin is not explained as a native tool',()=>{const r=analyze('function f(Number) { return Number.isFinite(2); }','x.js');assert.equal(r.status,'ready');const b=r.blocks[0];assert.ok(b.symbols.some(x=>x.name==='Number'&&x.origin==='作者命名的输入'));assert.doesNotMatch(b.output,/不先转换类型/);});
test('unrecognized languages and empty source do not get fabricated explanatory cards',()=>{for(const [code,name]of [['fn main() {}','x.rs'],['totally unrecognized ???',''],['','']]){const r=analyze(code,name,py);assert.ok(['unsupported','empty'].includes(r.status));assert.deepEqual(r.blocks,[]);}});
const samples=JSON.parse(fs.readFileSync(path.join(__dirname,'corpus/manifest.json'),'utf8'));
for(const sample of samples){test('corpus stability and source evidence: '+sample.name,()=>{const original=corpus(sample.name);let base;for(const variant of [original,'\n'+original,original.replace(/\r?\n/g,'\r\n')]){const r=analyze(variant,sample.name,py);assert.ok(['ready','partial'].includes(r.status),r.warnings.join(';'));assert.ok(r.blocks.length);assert.ok(r.blocks.length<=60);for(const b of r.blocks){assert.ok(b.start>=1&&b.end>=b.start&&b.end<=variant.split('\n').length);assert.equal(b.code,variant.split('\n').slice(b.start-1,b.end).join('\n'));assert.ok(b.purpose.length>10);assert.ok(!b.purpose.includes('这里是文件级别的代码'));}if(base)assert.deepEqual(r.blocks.map(b=>b.kind),base);else base=r.blocks.map(b=>b.kind);}});}
test('incomplete inputs return bounded results without exceptions',()=>{for(const sample of samples){const code=corpus(sample.name);for(const fraction of [0.2,0.55,0.9]){const r=analyze(code.slice(0,Math.floor(code.length*fraction)),sample.name,py);assert.ok(r&&Array.isArray(r.blocks));assert.ok(r.blocks.length<=60);}}});
