const {test}=require('node:test'),assert=require('node:assert/strict');
const {build,markdown}=require('../public/presentation');
const data={mode:'local',purpose:'计算结果。',blocks:[{start:2,end:6,title:'计算金额',purpose:'把价格加起来。',inputs:'价格',output:'金额'},{start:3,end:4,title:'循环',purpose:'逐项相加。'},...Array.from({length:7},(_,i)=>({start:10+i,end:10+i,title:'步骤'+i,purpose:'读取设置。'}))]};
test('presentation uses non-nested blocks, bounded duration and absolute source lines',()=>{const p=build(data,{duration:'30',offset:20,coverage:'highlights'});assert.equal(p.sections.length,4);assert.equal(p.sections[1].start,22);assert.equal(p.sections[1].end,26);assert.equal(p.sections[1].index,0);assert.ok(!p.sections.some(s=>s.title==='循环'));assert.match(markdown(p),/第 22—26 行/);assert.ok(build(data,{duration:'300'}).sections.length>p.sections.length);});
test('speaker notes do not invent runtime validation or author motivation',()=>{const p=build(data);assert.match(p.sections.at(-1).text,/没有执行代码/);assert.match(p.sections[0].text,/不等于实际调用顺序/);assert.match(p.questions[0].answer,/不能据此确认作者/);});
test('unsupported results have no fabricated speech and AI retains uncertainty',()=>{assert.equal(build({blocks:[]}).sections.length,0);assert.match(build({...data,mode:'ai'}).note,/需核对/);assert.match(build(data,{audience:'review'}).note,/代码评审/);});
test('Python speech describes actual updates and conditional flow without executing',()=>{const {analyze}=require('../analyzer');const result=analyze('def total(values):\n    amount = 0\n    for value in values:\n        if value > 0:\n            amount += value\n    return amount\n','example.py',process.env.CODELINGO_PYTHON||'python');const p=build(result);assert.match(p.sections[1].text,/amount.*设为 0/);assert.match(p.sections[1].text,/如果 value 大于 0/);assert.match(p.sections[1].text,/amount 加上 value/);assert.match(p.sections[1].text,/交回/);});
test('real presentation source keeps clean, build and markdown inside its wrapper',()=>{const fs=require('node:fs'),{analyze}=require('../analyzer');const code=fs.readFileSync(require.resolve('../public/presentation'),'utf8');const r=analyze(code,'presentation.js');const p=build(r,{duration:'30'});for(const name of ['clean','build','markdown'])assert.ok(p.sections.some(s=>s.title===name),name);assert.ok(!p.sections.some(s=>s.title==='临时使用的功能'));assert.match(p.note,/完整覆盖/);assert.match(p.sections.find(s=>s.title==='build').text,/准备|如果|交回/);});
test('damaged JavaScript cannot produce a presentation from recovered fragments',()=>{const {analyze}=require('../analyzer');const r=analyze('```javascript\nfunction build() { return “broken”; }\n```','presentation.js');assert.ok(r.syntaxErrors||r.inputFormatIssue);const p=build(r);assert.equal(p.sections.length,0);assert.match(p.note,/暂停/);assert.ok(p.diagnostics.length);});
