const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {analyze}=require('../analyzer'),{modules,flowNodes}=require('../public/structure');const python=process.env.CODELINGO_PYTHON||'python';
test('both returning branches stop the sequence; an absent else can continue',()=>{let r=analyze('function choose(x){if(x){return 1;}else{return 2;} unreachable();}','x.js');const f=r.blocks.find(b=>b.title==='choose').controlFlow;assert.equal(f.length,1);assert.equal(f[0].terminal,true);assert.equal(f[0].children[0].kind,'return');assert.equal(f[0].otherwise[0].kind,'return');r=analyze('function choose(x){if(x)return 1; return 2;}','x.js');assert.equal(r.blocks.find(b=>b.title==='choose').controlFlow.length,2);});
test('loops retain continue, break and loop else as distinct paths',()=>{const code='def run(items):\n    for item in items:\n        if item < 0:\n            continue\n        if item == 0:\n            break\n    else:\n        return 1\n    return 2\n';const r=analyze(code,'x.py',python);const f=r.blocks.find(b=>b.title==='run').controlFlow;assert.equal(f[0].kind,'loop');assert.equal(f[0].afterLoop[0].kind,'return');assert.ok(flowNodes(f).some(n=>n.kind==='break'));assert.ok(flowNodes(f).some(n=>n.kind==='continue'));assert.equal(f[1].kind,'return');});
test('partial Python recovery shifts every nested flow node to original lines',()=>{const r=analyze('broken = (\n','x.py',python);assert.equal(modules(r).length,0);const code='def good(x):\n    if x:\n        return 1\n\ndef bad(:\n    pass';const s=analyze(code,'x.py',python);assert.ok(s.partialRecovery);assert.equal(s.blocks.find(b=>b.title==='good').controlFlow[0].children[0].start,3);});
test('callbacks do not hide named modules and complex exception flow stays explicit',()=>{const r=analyze('(function(){function a(){try{go()}catch(e){recover()}}function b(){return 1}})();','x.js');assert.deepEqual(modules(r).map(x=>x.block.title),['a','b']);assert.equal(modules(r)[0].block.controlFlow[0].kind,'exception');assert.equal(modules(r)[0].block.controlFlow[0].handlers.length,1);});
const dir=path.join(__dirname,'corpus'),manifest=JSON.parse(fs.readFileSync(path.join(dir,'manifest.json'),'utf8'));
test('real binary search has a loop with branching; real number check has early returns',()=>{const py=analyze(fs.readFileSync(path.join(dir,'binary-search.py'),'utf8'),'binary-search.py',python);const fn=py.blocks.find(x=>x.title==='bisect_left');const loop=fn.controlFlow.find(x=>x.kind==='loop');assert.ok(loop);assert.ok(loop.children.some(x=>x.kind==='condition'));assert.ok(flowNodes(fn.controlFlow).every(n=>n.label.trim()));const js=analyze(fs.readFileSync(path.join(dir,'is-number.js'),'utf8'),'is-number.js');const f=js.blocks.find(x=>x.title==='module.exports').controlFlow;assert.deepEqual(f.map(x=>x.kind),['condition','condition','return']);assert.ok(f[0].children[0].terminal&&f[1].children[0].terminal);});
for(const item of manifest)test('real corpus graph evidence and newline stability: '+item.name,()=>{const raw=fs.readFileSync(path.join(dir,item.name),'utf8').replace(/\r\n/g,'\n');let base;
 for(const [variant,offset]of [[raw,0],['\n'+raw,1],[raw.replace(/\n/g,'\r\n'),0]]){const r=analyze(variant,item.name,python),selected=modules(r);assert.ok(selected.length);const titles=selected.map(x=>x.block.title);if(!base)base=titles;else assert.deepEqual(titles,base);
  for(const {block:b,index}of selected){assert.equal(r.blocks[index],b);for(const n of flowNodes(b.controlFlow)){assert.ok(n.start>=b.start&&n.end<=b.end&&n.end>=n.start);assert.ok(variant.split('\n').slice(n.start-1,n.end).join('\n').trim());if(n.kind==='condition'){assert.ok(Array.isArray(n.children)&&Array.isArray(n.otherwise));}if(n.kind==='return')assert.ok(n.terminal);}}
 }
});

