const parse5=require('parse5'),postcss=require('postcss');const {Parser}=require('node-sql-parser');const {block,result,symbol}=require('./common');
function html(code){const errors=[],tree=parse5.parse(code,{sourceCodeLocationInfo:true,onParseError:e=>errors.push(e)}),blocks=[];
 const help={title:'设置浏览器标签页上的标题。',h1:'显示页面的一级标题。',h2:'显示二级标题，把页面分成较小章节。',p:'显示一段文字。',a:'提供一个可以点击的链接。',img:'在页面中放入一张图片。',button:'显示按钮；点击后实际做什么还要看表单或 JavaScript。',input:'让用户输入或选择内容。',form:'把用户填写的内容组织成表单。',script:'引用或包含 JavaScript；这里只标记位置，不执行其中代码。',link:'引用外部资源，例如样式表。',ul:'组织一组无序列表项目。',ol:'组织一组有顺序的列表项目。',nav:'标记导航区域。',main:'标记页面的主要内容。',section:'把相关内容划分成一个区域。'};
 function visit(n){const loc=n.sourceCodeLocation;if(loc&&help[n.tagName]){const attrs=Object.fromEntries((n.attrs||[]).map(a=>[a.name,a.value]));const content=(n.childNodes||[]).filter(x=>x.nodeName==='#text').map(x=>x.value.trim()).filter(Boolean).join(' ').slice(0,100);let purpose=help[n.tagName];if(attrs.href)purpose+=' 目标：'+attrs.href+'。';if(attrs.src)purpose+=' 来源：'+attrs.src+'。';if(attrs.alt)purpose+=' 图片文字说明：'+attrs.alt+'。';if(content)purpose+=' 可见文字：'+content+'。';
 blocks.push(block(code,loc.startOffset,loc.endOffset||loc.startTag?.endOffset,'element',`<${n.tagName}>${content?' · '+content:''}`,purpose,{symbols:[symbol(n.tagName,'HTML 规定的标签',help[n.tagName],'标签名有固定意义；不能换成任意词。'),...Object.entries(attrs).map(([k,v])=>symbol(k,['class','id'].includes(k)?'固定属性，值由作者命名':'HTML 属性',`${k} 当前填写为 ${v}。${['class','id'].includes(k)?'它可供样式和脚本寻找这个元素。':''}`,['class','id'].includes(k)?'属性名不变；修改值时同步修改引用它的样式和脚本。':'按 HTML 规则填写；改变值会改变相关行为。'))],concept:'HTML 描述页面有什么内容；样式和交互通常分别由 CSS 与 JavaScript 补充。'}));}for(const c of n.childNodes||[])visit(c);}visit(tree);
 const warnings=errors.filter(e=>e.code!=='missing-doctype').map(e=>`第 ${e.startLine} 行：${e.code}（HTML 解析器可能自动补全结构，请核对原文）`).slice(0,6);
 return result('HTML','HTML 语法解析',`这份页面结构中识别到 ${blocks.length} 个可讲解的内容或资源元素。`,'按标题、文字、图片、链接、输入等功能阅读。不会加载引用资源，也不会执行脚本。',blocks,warnings,warnings.length?'partial':'ready');}
const cssHelp={color:'文字颜色','background-color':'背景颜色',background:'背景设置','font-size':'文字大小','font-weight':'文字粗细',display:'元素如何参与布局',margin:'外部间距',padding:'内容与边框之间的间距',width:'宽度',height:'高度',position:'定位方式',border:'边框',opacity:'透明程度','border-radius':'圆角','text-align':'文字对齐方式','line-height':'行高',overflow:'内容超出区域后的处理方式','box-sizing':'宽高是否包含内边距和边框'};
function css(code){let root;try{root=postcss.parse(code,{map:false});}catch(e){return result('CSS','CSS 语法解析','样式没有完整解析','请检查花括号、注释和属性值。',[],[`第 ${e.line} 行：${e.reason}`],'invalid');}
 const blocks=[];root.walkRules(n=>{const props=(n.nodes||[]).filter(x=>x.type==='decl');let target=n.selector.startsWith('.')?'class 名称匹配的元素':n.selector.startsWith('#')?'id 匹配的元素':'匹配这个选择规则的元素';blocks.push(block(code,n.source.start.offset,n.source.end.offset+1,'style',`设置 ${n.selector.replace(/\s+/g,' ').slice(0,110)} 的样式`,`${target}会应用以下设置：\n`+props.slice(0,14).map(p=>`${cssHelp[p.prop]||p.prop}：${p.value}${p.important?'（带 !important 标记）':''}`).join('\n'),{usage:'先在 HTML 中找到匹配的元素，再对照这些值观察变化。实际结果也受其他规则和优先级影响。',symbols:[symbol(n.selector,'选择规则','指定这些样式作用到哪些元素。','类名和 id 可由作者命名，修改时需要同步 HTML/脚本引用。'),...props.slice(0,14).map(p=>symbol(p.prop,p.prop.startsWith('--')?'作者定义的样式变量':'CSS 属性',cssHelp[p.prop]||'需要按对应 CSS 规范理解的样式设置。',p.prop.startsWith('--')?'可以改名，但 var() 引用也要一起改。':'属性名称按 CSS 规则填写；通常修改右侧的值。'))]}));});
 root.walkAtRules(n=>{if(n.name==='media'||n.name==='supports')blocks.push(block(code,n.source.start.offset,n.source.end.offset+1,'condition',`样式生效条件：@${n.name}`,`只有满足 ${n.params} 这项条件时，内部规则才参与样式计算。`));});
 return result('CSS','CSS 语法解析',`这份样式表有 ${blocks.length} 个样式规则或生效条件。`,'按“作用到谁 → 改变什么 → 设置什么值”阅读。这里不执行网页，也不保证每条规则最终胜出。',blocks);}
function splitSQL(code){let start=0,q='',comment='',parts=[];for(let i=0;i<code.length;i++){const c=code[i],next=code[i+1];if(comment==='line'){if(c==='\n')comment='';continue;}if(comment==='block'){if(c==='*'&&next==='/'){comment='';i++;}continue;}if(q){if(c===q){if(next===q)i++;else q='';}continue;}if(c==='-'&&next==='-'){comment='line';i++;continue;}if(c==='/'&&next==='*'){comment='block';i++;continue;}if(c==="'"||c==='"'||c==='`'){q=c;continue;}if(c===';'){if(code.slice(start,i+1).trim())parts.push([start,i+1]);start=i+1;}}if(code.slice(start).trim())parts.push([start,code.length]);return parts;}
function sql(code){let ast,dialect,err;for(const db of ['sqlite','Postgresql','MySQL']){try{ast=new Parser().astify(code,{database:db});dialect=db;break;}catch(e){err=e;}}if(!ast)return require('./sql-recovery').recover(code,splitSQL(code),err);
 const statements=Array.isArray(ast)?ast:[ast],ranges=splitSQL(code),blocks=[];
 for(let i=0;i<statements.length;i++){const s=statements[i],type=s.type?.toLowerCase();let title='数据库操作：'+type,purpose='按下面的 SQL 语句处理数据库，具体语义需要结合表结构。';const tables=(s.table||s.from||[]);const names=Array.isArray(tables)?tables.map(t=>t.table).filter(Boolean).join('、'):'';
  if(type==='select'){title='查询数据'+(names?'：'+names:'');purpose=`从 ${names||'语句指定的数据来源'} 读取结果${s.where?'，先按 WHERE 条件筛选':''}${s.groupby?'，按 GROUP BY 分组':''}${s.orderby?'，按 ORDER BY 排序':''}${s.limit?.value?.length?'，限制返回数量':''}。这描述的是查询逻辑，不是保证数据库按该文字顺序执行。`;}
  if(type==='create'){title='建立数据库结构'+(names?'：'+names:'');purpose=`创建 ${names||s.keyword||'语句指定的结构'}，并定义里面的字段或约束。`;}
  if(type==='insert'){title='添加数据'+(names?'：'+names:'');purpose='向指定表加入新记录；实际写入受表结构和约束影响。';}
  if(type==='update'){title='修改已有数据'+(names?'：'+names:'');purpose='修改匹配条件的记录。'+(s.where?'有 WHERE 筛选条件。':'未看到 WHERE 条件，可能影响整张表。');}
  if(type==='delete'){title='删除记录'+(names?'：'+names:'');purpose='删除指定表中的记录。'+(s.where?'有 WHERE 筛选条件。':'未看到 WHERE 条件，可能删除整张表的记录。');}
  const [a,b]=ranges.length===statements.length?ranges[i]:[0,code.length];blocks.push(block(code,a,b,'query',title,purpose,{usage:'先确认表名、字段和条件。此软件只读取语句，不连接或修改数据库。',symbols:[symbol(type.toUpperCase(),'SQL 关键字','规定进行哪类数据库操作。','关键字按数据库语法填写；表名和字段名按你的数据库定义。')]}));
 }
 return result('SQL','SQL 语法解析',`识别到 ${blocks.length} 条数据库语句。`,`按 ${dialect} 语法成功读取；这不证明你的目标数据库一定兼容，也不验证表和字段是否存在。`,blocks);}
module.exports={html,css,sql};
